sudo: required
language: python
python:
  - "3.6"
addons:
  apt:
    update: true
before_install:
  - sudo apt install sdcc
install:
  - "(cd vendor/libfx2/software && SDAR='sdcclib r' python setup.py install)"
  - "(cd vendor && git clone git://github.com/m-labs/migen.git && cd migen && python setup.py install)"
script:
  - "(cd software && python setup.py install)"
  - "(cd software && python setup.py test)"
notifications:
  irc:
    channels:
      - "chat.freenode.net##openfpga"
    use_notice: true
    skip_join: true
